//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work1
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public employees()
        {
            this.employees1 = new HashSet<employees>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public int team_id { get; set; }
        public int role_id { get; set; }
        public Nullable<int> team_leader_id { get; set; }
    
        public virtual ICollection<employees> employees1 { get; set; }
        public virtual employees employees2 { get; set; }
        public virtual roles roles { get; set; }
        public virtual teams teams { get; set; }
        public override string ToString()
        {
            return (id + " " + first_name + " " + last_name + " " + email + " " + team_id + " " + role_id + " " + team_leader_id);
        }
    }
}
