//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work1
{
    using System;
    using System.Collections.Generic;
    
    public partial class teams
    {
        public teams()
        {
            this.employees = new HashSet<employees>();
            this.team_skills = new HashSet<team_skills>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<employees> employees { get; set; }
        public virtual ICollection<team_skills> team_skills { get; set; }
    }
}
