//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace work1
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_skills
    {
        public int id { get; set; }
        public int team_id { get; set; }
        public int skill_id { get; set; }
    
        public virtual skills skills { get; set; }
        public virtual teams teams { get; set; }
    }
}
